on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    if: ${{ !contains(github.event.head_commit.message, 'merge:') }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Coding-with-Frigeri/test-coverage-dashboard@master
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Adding a new file for testing purposes
        uses: EndBug/add-and-commit@v9
        with:
          add: './test.json'
          message: 'merge: add new file to the project'
