on:
  push:
    branches:
      - master
      - charts_display

jobs:
  hello_world_job:
    if: ${{ !contains(github.event.head_commit.message, 'merge:') }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Run Test Coverage
        run: npm run test
      - name: Try to run action.yml
        id: run
        uses: ./
      - name: Adding a new file for testing purposes
        uses: EndBug/add-and-commit@v9
        with:
          add: './data.json'
          message: 'merge: update data.json file by overwriting it'
